// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 03/24/2017 18:50:57+0000
package com.systemsjr.basekolo.level.web.search;

import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import javax.faces.context.FacesContext;

import com.systemsjr.basekolo.level.vo.LevelSearchCriteria;
import com.systemsjr.basekolo.level.vo.LevelVO;

/**
 * @see com.systemsjr.basekolo.level.web.search.LevelSearchController
 */
public class LevelSearchControllerImpl
    extends LevelSearchController
{
    /*
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4762704454092021123L;

    /**
     * @see com.systemsjr.basekolo.level.web.search.LevelSearchController#populateSearchScreen(LevelSearchCriteria searchCriteria)
     */
    @Override
    public void initialiseSearchScreen(InitialiseSearchScreenForm form)
    {
    	
    }

	@Override
	public void doLevelDetails(DoLevelDetailsForm form) throws Throwable {
		LevelVO level =  (LevelVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
		if(level != null) {
			level = getLevelService().findById(level.getId());		
			form.setLevelVO(level);
			FacesContext.getCurrentInstance().getExternalContext().getFlash().put("levelVO", level);
		}
	}

	@Override
	public void doLevelEdit(DoLevelEditForm form) throws Throwable {
		LevelVO level =  (LevelVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
		if(level != null) {
			level = getLevelService().findById(level.getId());		
			form.setLevelVO(level);
			this.getSearchLevelsEditForm().setLevelVO(level);
			FacesContext.getCurrentInstance().getExternalContext().getFlash().put("levelVO", level);
		}
	}

	@Override
	public void doLevelsSearch() throws Throwable {
    	getSearchLevelsSearchForm().setLevelLists(getLevelService().levelSearch(getSearchLevelsSearchForm().getSearchCriteria()));
	}

	@Override
	public void exitLevelSearch() throws Throwable {
		
		
	}

}