// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 03/24/2017 21:41:52+0000
package com.systemsjr.basekolo.level.web.details;

import javax.faces.context.FacesContext;

import com.systemsjr.basekolo.level.vo.LevelVO;

/**
 * @see com.systemsjr.basekolo.level.web.details.LevelDetailsController
 */
public class LevelDetailsControllerImpl
    extends LevelDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6220716463733511848L;

	@Override
	public void initialiseDetailsScreen(InitialiseDetailsScreenForm form) throws Throwable {
		LevelVO levelVO = (LevelVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("levelVO");
		if(levelVO != null) {
			form.setLevelVO(levelVO);
		}
	}

	@Override
	public void doLevelEdit(DoLevelEditForm form) throws Throwable {
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("levelVO", form.getLevelVO());
	}

}