// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 04/21/2018 13:28:15+0100
package com.systemsjr.basekolo.student.web.edit;

import com.systemsjr.basekolo.level.instance.vo.LevelInstanceVO;
import com.systemsjr.basekolo.student.vo.StudentVO;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

/**
 * @see com.systemsjr.basekolo.student.web.edit.StudentEditController
 */
public class StudentEditControllerImpl
    extends StudentEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 799382378627218023L;

    /**
     * @see com.systemsjr.basekolo.student.web.edit.StudentEditController#initialiseEditScreen(StudentVO studentVO)
     */
    @Override
    public void initialiseEditScreen(InitialiseEditScreenForm form)
    {

		//Collection<LevelVO> levels = get;
		//LevelInstanceSearchCriteria searchCriteria = new LevelInstanceSearchCriteria();
		//searchCriteria.set
		Collection<LevelInstanceVO> instances = getLevelInstanceService().getAllLevelInstances();
		final Collection<SelectItem> levelInstancesBackingList=new ArrayList<SelectItem>();
		for(LevelInstanceVO instance : instances) {
			levelInstancesBackingList.add(new SelectItem(instance.getId(), instance.getInstanceName()));			
		}

		StudentVO studentVO = (StudentVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("studentVO");
		if(studentVO != null) {
			if(studentVO.getId() != null) {
				studentVO = getStudentService().findById(studentVO.getId());
			}
		} else {
			studentVO = new StudentVO();
		}
		
		if(studentVO.getStudentClass() == null) {
			studentVO.setStudentClass(new LevelInstanceVO());
		}
		
		getEditStudentSaveForm().setStudentVOStudentClassBackingList(levelInstancesBackingList);
		getEditStudentSaveForm().setStudentVO(studentVO);
    }

    /**
     * @see com.systemsjr.basekolo.student.web.edit.StudentEditController#doSaveStudent()
     */
    @Override
    public void doSaveStudent()
    {
    	StudentVO studentVO = getEditStudentSaveForm().getStudentVO();
        if(studentVO.getId() == null){
        	studentVO.setCreatedAt(new Date());
        	studentVO.setCreatedBy("system");
    	} else {
    		studentVO.setModifiedAt(new Date());
    		studentVO.setModifiedBy("system");
    	}

        studentVO = getStudentService().saveStudent(studentVO);
        getEditStudentSaveForm().setStudentVO(studentVO);
        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("studentVO", studentVO);
    }

    /**
     * @see com.systemsjr.basekolo.student.web.edit.StudentEditController#doNewStudent()
     */
    @Override
    public void doNewStudent()
    {
    	StudentVO studentVO = new StudentVO();
    	getEditStudentForm().setStudentVO(studentVO);
    }

}