// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 03/26/2017 14:17:42+0100
package com.systemsjr.basekolo.level.instance.web.details;

import javax.faces.context.FacesContext;

import com.systemsjr.basekolo.level.instance.vo.LevelInstanceVO;

/**
 * @see com.systemsjr.basekolo.level.web.details.instance.LevelInstanceDetailsController
 */
public class LevelInstanceDetailsControllerImpl
    extends LevelInstanceDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -8161277304285479959L;

    /**
     * @see com.systemsjr.basekolo.level.web.details.instance.LevelInstanceDetailsController#initialiseDetailsScreen(LevelInstanceVO levelInstanceVO)
     */
    @Override
    public void initialiseDetailsScreen(InitialiseDetailsScreenForm form)
    {
		LevelInstanceVO levelInstanceVO = (LevelInstanceVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("levelInstanceVO");
		if(levelInstanceVO != null) {
			form.setLevelInstanceVO(levelInstanceVO);
		}
    }

	@Override
	public void doLevelInstanceEdit(DoLevelInstanceEditForm form) throws Throwable {
		
		LevelInstanceVO instanceVO = form.getLevelInstanceVO();
		instanceVO.setStudents(getStudentService().findClassStudents(instanceVO.getId()));
		
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("levelInstanceVO", form.getLevelInstanceVO());
		
	}

	@Override
	public void exitProgressLevelInstance() throws Throwable {
		// TODO Auto-generated method stub
		
	}

}