// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 04/21/2018 13:28:15+0100
package com.systemsjr.basekolo.student.web.details;

import com.systemsjr.basekolo.student.vo.StudentVO;
import java.util.Date;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.basekolo.student.web.details.StudentDetailsController
 */
public class StudentDetailsControllerImpl
    extends StudentDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7864656149625706287L;

    /**
     * @see com.systemsjr.basekolo.student.web.details.StudentDetailsController#initialiseDetailsScreen(StudentVO studentVO)
     */
    @Override
    public void initialiseDetailsScreen(InitialiseDetailsScreenForm form)
    {
    	StudentVO studentVO = (StudentVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("studentVO");
		if(studentVO != null) {
			form.setStudentVO(studentVO);
		}
    }

}