// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 04/21/2018 13:28:15+0100
package com.systemsjr.basekolo.student.web.search;

import com.systemsjr.basekolo.student.vo.StudentSearchCriteria;
import com.systemsjr.basekolo.student.vo.StudentVO;
import java.util.Date;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.basekolo.student.web.search.StudentSearchController
 */
public class StudentSearchControllerImpl
    extends StudentSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5660223435122585231L;

    /**
     * @see com.systemsjr.basekolo.student.web.search.StudentSearchController#initialiseSearchScreen(StudentSearchCriteria searchCriteria)
     */
    @Override
    public void initialiseSearchScreen(InitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.basekolo.student.web.search.StudentSearchController#doStudentDetails(java.lang.Long id, StudentVO studentVO)
     */
    @Override
    public void doStudentDetails(DoStudentDetailsForm form)
    {

    	StudentVO studentVO =  (StudentVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
		if(studentVO != null) {
			studentVO = getStudentService().findById(studentVO.getId());		
			form.setStudentVO(studentVO);
			FacesContext.getCurrentInstance().getExternalContext().getFlash().put("studentVO", studentVO);
		}
    }

    /**
     * @see com.systemsjr.basekolo.student.web.search.StudentSearchController#doStudentEdit(java.lang.Long id, StudentVO studentVO)
     */
    @Override
    public void doStudentEdit(DoStudentEditForm form)
    {
    	StudentVO studentVO =  (StudentVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
		if(studentVO != null) {
			studentVO = getStudentService().findById(studentVO.getId());		
			form.setStudentVO(studentVO);
			this.getSearchStudentsEditForm().setStudentVO(studentVO);
			FacesContext.getCurrentInstance().getExternalContext().getFlash().put("studentVO", studentVO);
		}
    }

    /**
     * @see com.systemsjr.basekolo.student.web.search.StudentSearchController#doStudentsSearch()
     */
    @Override
    public void doStudentsSearch()
    {
    	getSearchStudentsSearchForm().setStudentLists(getStudentService().studentSearch(getSearchStudentsForm().getSearchCriteria()));
    }

}